import type { AdminPost } from './types';

// LOCAL_UI_SAMPLE ONLY.
// These records exist only to exercise the legacy Teacher/Admin UI in Phase 1.
// They are not research evidence, historical production records or migration input.
export const INITIAL_ADMIN_POSTS:AdminPost[] = [
  {
    id:'ADM-001', title:'Sách giáo khoa Vật lí 12 - bộ Kết nối tri thức',
    description:'Sách đã dùng một học kỳ, có bọc bìa, vài trang có ghi chú bằng bút chì. Không rách, không thiếu trang.',
    tradeType:'Bán giá rẻ', category:'Sách giáo khoa', className:'12A1', name:'Nguyễn Minh An',
    email:'minhan.local@edushare.test', emailMasked:'min***@edushare.test', contactInfo:'Nhắn qua email trường sau khi xem liên hệ.',
    price:45000, date:'11/08/2026 08:42', dateTs:1723340520000, status:'Chờ duyệt', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:0, reportCount:0, imageUrl:'/assets/local-ui-books.jpg', favoriteCount:0, contactCount:0, viewCount:4,
  },
  {
    id:'ADM-002', title:'Máy tính Casio fx-580VN X còn tốt',
    description:'Máy hoạt động bình thường, phím rõ, có nắp. Pin mới thay gần đây. Phù hợp cho học sinh lớp 10-12.',
    tradeType:'Bán giá rẻ', category:'Dụng cụ học tập', className:'12A2', name:'Trần Gia Hân',
    email:'giahan.local@edushare.test', emailMasked:'gia***@edushare.test', contactInfo:'Liên hệ tại lớp 12A2 giờ ra chơi.',
    price:320000, date:'11/08/2026 07:35', dateTs:1723336500000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:4, reportCount:0, favoriteCount:8, contactCount:6, viewCount:58,
  },
  {
    id:'ADM-003', title:'Combo vở ghi 200 trang còn mới',
    description:'4 cuốn vở, mới dùng rất ít. Cho tặng bạn nào cần để ghi bài đầu năm.',
    tradeType:'Cho tặng', category:'Vở', className:'11A3', name:'Lê Ngọc Mai',
    email:'ngocmai.local@edushare.test', emailMasked:'ngo***@edushare.test', contactInfo:'Có thể nhận tại thư viện.',
    price:0, date:'10/08/2026 20:15', dateTs:1723295700000, status:'Chờ duyệt', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:1, reportCount:0, favoriteCount:2, contactCount:0, viewCount:13,
  },
  {
    id:'ADM-004', title:'Áo thể dục size L cần đổi size M',
    description:'Áo sạch, còn tốt, muốn đổi sang size M. Có ảnh mặt trước và nhãn size.',
    tradeType:'Trao đổi', category:'Đồng phục', className:'10A4', name:'Phạm Hoàng Long',
    email:'hoanglong.local@edushare.test', emailMasked:'hoa***@edushare.test', contactInfo:'Trao đổi tại lớp 10A4.',
    price:0, date:'10/08/2026 18:02', dateTs:1723287720000, status:'Từ chối', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:0, reportCount:0, rejectionReason:'Ảnh minh họa chưa đủ rõ để đối chiếu tình trạng đồng phục.', favoriteCount:0, contactCount:0, viewCount:0,
  },
  {
    id:'ADM-005', title:'Sách tham khảo Toán 11 chuyên đề hàm số',
    description:'Sách còn đủ trang, có một số đánh dấu bằng highlight. Giá mong muốn thấp hơn giá mua ban đầu.',
    tradeType:'Bán giá rẻ', category:'Sách tham khảo', className:'11A1', name:'Đỗ Khánh Linh',
    email:'khanhlinh.local@edushare.test', emailMasked:'kha***@edushare.test', contactInfo:'Ưu tiên trao đổi trực tiếp trong trường.',
    price:70000, date:'10/08/2026 16:46', dateTs:1723283160000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:7, reportCount:2, favoriteCount:10, contactCount:9, viewCount:79,
  },
  {
    id:'ADM-006', title:'Bộ bút marker 8 màu',
    description:'Còn 6/8 bút viết tốt. Cho mượn trong 2 tuần để làm poster dự án.',
    tradeType:'Cho mượn', category:'Bút', className:'10A2', name:'Vũ Minh Châu',
    email:'minhchau.local@edushare.test', emailMasked:'min***@edushare.test', contactInfo:'Nhận/trả tại phòng CLB.',
    price:0, date:'10/08/2026 14:20', dateTs:1723274400000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Tắt', commentCount:3, reportCount:0, favoriteCount:3, contactCount:2, viewCount:34,
  },
  {
    id:'ADM-007', title:'Tai nghe có dây dùng học ngoại ngữ',
    description:'Tai nghe 3.5mm hoạt động tốt, đệm tai đã cũ nhẹ. Cho tặng bạn cần học nghe.',
    tradeType:'Cho tặng', category:'Đồ điện tử nhỏ', className:'12A3', name:'Nguyễn Anh Khoa',
    email:'anhkhoa.local@edushare.test', emailMasked:'anh***@edushare.test', contactInfo:'Nhận ở khu A.',
    price:0, date:'10/08/2026 12:11', dateTs:1723266660000, status:'Đang mở', source:'Posts', hidden:true,
    commentStatus:'Mở', commentCount:2, reportCount:1, favoriteCount:4, contactCount:5, viewCount:46,
  },
  {
    id:'ADM-008', title:'Sách giáo khoa Hóa học 11',
    description:'Đã hoàn tất trao đổi trong phiên dữ liệu UI local.',
    tradeType:'Trao đổi', category:'Sách giáo khoa', className:'11A2', name:'Đặng Thu Trang',
    email:'thutrang.local@edushare.test', emailMasked:'thu***@edushare.test', contactInfo:'Đã hoàn tất.',
    price:0, date:'09/08/2026 09:05', dateTs:1723169100000, doneAt:'10/08/2026 09:30', status:'Đã xong', source:'Archive', hidden:false,
    commentStatus:'Tắt', commentCount:5, reportCount:0, favoriteCount:6, contactCount:4, viewCount:61,
  },
  {
    id:'ADM-009', title:'Bộ compa và thước kỹ thuật',
    description:'Đủ compa, thước 20cm và eke. Hộp nhựa xước nhẹ.',
    tradeType:'Bán giá rẻ', category:'Dụng cụ học tập', className:'10A1', name:'Bùi Quang Huy',
    email:'quanghuy.local@edushare.test', emailMasked:'qua***@edushare.test', contactInfo:'Liên hệ qua email.',
    price:35000, date:'09/08/2026 08:30', dateTs:1723167000000, status:'Chờ duyệt', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:0, reportCount:0, favoriteCount:0, contactCount:0, viewCount:2,
  },
  {
    id:'ADM-010', title:'Tập giấy A4 một mặt để làm nháp',
    description:'Giấy in một mặt, mặt còn lại sạch. Cho tặng để làm nháp hoặc luyện bài.',
    tradeType:'Cho tặng', category:'Khác', className:'12A1', name:'Hoàng Hà My',
    email:'hamy.local@edushare.test', emailMasked:'ham***@edushare.test', contactInfo:'Nhận ở lớp 12A1.',
    price:0, date:'08/08/2026 19:42', dateTs:1723120920000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:6, reportCount:0, favoriteCount:7, contactCount:7, viewCount:70,
  },
  {
    id:'ADM-011', title:'Sách luyện IELTS đã dùng',
    description:'Sách có ghi chú nhiều bằng bút mực. Muốn bán lại để mua tài liệu mới.',
    tradeType:'Bán giá rẻ', category:'Sách tham khảo', className:'12A4', name:'Phan Thu Uyên',
    email:'thuyen.local@edushare.test', emailMasked:'thu***@edushare.test', contactInfo:'Liên hệ email.',
    price:150000, date:'08/08/2026 16:16', dateTs:1723108560000, status:'Từ chối', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:0, reportCount:0, rejectionReason:'Mô tả tình trạng cần nêu rõ hơn phần đã ghi chú và ảnh bên trong sách.', favoriteCount:0, contactCount:0, viewCount:0,
  },
  {
    id:'ADM-012', title:'Balo học sinh còn sử dụng tốt',
    description:'Khóa kéo hoạt động bình thường, có vết xước nhẹ ở đáy. Đã vệ sinh trước khi đăng.',
    tradeType:'Bán giá rẻ', category:'Khác', className:'11A3', name:'Nguyễn Đức Nam',
    email:'ducnam.local@edushare.test', emailMasked:'duc***@edushare.test', contactInfo:'Xem hàng tại khuôn viên trường.',
    price:90000, date:'08/08/2026 13:30', dateTs:1723098600000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:2, reportCount:0, favoriteCount:5, contactCount:3, viewCount:42,
  },
  {
    id:'ADM-013', title:'Sách Ngữ văn 10 đã hoàn tất cho tặng',
    description:'Đã hoàn tất trong dữ liệu UI local.',
    tradeType:'Cho tặng', category:'Sách giáo khoa', className:'10A3', name:'Trịnh Minh Thư',
    email:'minhthu.local@edushare.test', emailMasked:'min***@edushare.test', contactInfo:'Đã hoàn tất.',
    price:0, date:'07/08/2026 10:05', dateTs:1722996300000, doneAt:'08/08/2026 11:10', status:'Đã xong', source:'Archive', hidden:false,
    commentStatus:'Tắt', commentCount:4, reportCount:0, favoriteCount:4, contactCount:5, viewCount:54,
  },
  {
    id:'ADM-014', title:'Hộp màu nước 12 màu',
    description:'Còn khoảng 70%, phù hợp làm poster hoặc mỹ thuật. Muốn trao đổi lấy giấy vẽ.',
    tradeType:'Trao đổi', category:'Dụng cụ học tập', className:'10A2', name:'Lương Bảo Ngọc',
    email:'baongoc.local@edushare.test', emailMasked:'bao***@edushare.test', contactInfo:'Trao đổi tại CLB.',
    price:0, date:'07/08/2026 08:22', dateTs:1722990120000, status:'Đang mở', source:'Posts', hidden:false,
    commentStatus:'Mở', commentCount:3, reportCount:0, favoriteCount:5, contactCount:4, viewCount:49,
  },
];
