import type { MarketPost } from './types';

/**
 * Dữ liệu chỉ phục vụ kiểm tra UI/UX local ở Phase 1.
 * Không phải dữ liệu nghiên cứu, không phải dữ liệu migration và không được dùng cho báo cáo KHKT.
 */
export const LOCAL_UI_SAMPLE_POSTS: MarketPost[] = [
  { id:'UI-001', title:'Sách giáo khoa Vật lí 12 - bộ Kết nối tri thức', description:'Sách còn sạch, đủ trang, phù hợp học sinh lớp 12.', name:'Học sinh', className:'12A1', tradeType:'Cho tặng', category:'Sách giáo khoa', price:0, date:'10/08/2026 16:20', dateTs:1786353600000, hasImage:true, favoriteCount:12, ownerReputationScore:9.1, ownerReputationLabel:'Rất tốt', rankScore:92, aiScore:95, recommendationReason:'Đúng nhóm sách giáo khoa và được lưu nhiều.' },
  { id:'UI-002', title:'Máy tính Casio fx-570VN Plus còn sử dụng tốt', description:'Máy hoạt động bình thường, phím rõ và có nắp.', name:'Học sinh', className:'11A2', tradeType:'Bán giá rẻ', category:'Đồ điện tử nhỏ', price:220000, date:'10/08/2026 15:42', dateTs:1786351320000, hasImage:true, favoriteCount:18, ownerReputationScore:8.7, ownerReputationLabel:'Rất tốt', rankScore:96, aiScore:94, recommendationReason:'Bài có nhiều lượt lưu và phù hợp từ khóa Casio.' },
  { id:'UI-003', title:'Bộ compa, thước và ê-ke dùng cho môn Toán', description:'Bộ dụng cụ còn đủ chi tiết, phù hợp cho học sinh THPT.', name:'Học sinh', className:'10A4', tradeType:'Trao đổi', category:'Dụng cụ học tập', price:0, date:'10/08/2026 14:10', dateTs:1786345800000, hasImage:true, favoriteCount:7, ownerReputationScore:7.8, ownerReputationLabel:'Tốt', rankScore:81, aiScore:84, recommendationReason:'Bài mới, có ảnh minh họa và thuộc nhóm dụng cụ học tập.' },
  { id:'UI-004', title:'Cho mượn sách tham khảo Hóa học 11 trong học kỳ I', description:'Ưu tiên bạn cần dùng trong một học kỳ và giữ sách cẩn thận.', name:'Học sinh', className:'11A5', tradeType:'Cho mượn', category:'Sách tham khảo', price:0, date:'10/08/2026 12:55', dateTs:1786341300000, hasImage:false, favoriteCount:5, ownerReputationScore:8.2, ownerReputationLabel:'Rất tốt', rankScore:79, aiScore:86, recommendationReason:'Phù hợp nhu cầu mượn sách tham khảo trong thời gian ngắn.' },
  { id:'UI-005', title:'Đồng phục thể dục nam size L còn mới', description:'Áo và quần còn tốt, không rách, phù hợp học sinh THPT.', name:'Học sinh', className:'12A3', tradeType:'Bán giá rẻ', category:'Đồng phục', price:65000, date:'09/08/2026 20:30', dateTs:1786282200000, hasImage:true, favoriteCount:9, ownerReputationScore:6.8, ownerReputationLabel:'Tốt', rankScore:76, aiScore:80, recommendationReason:'Có ảnh và mức quan tâm ổn định trong nhóm đồng phục.' },
  { id:'UI-006', title:'Tặng bộ vở ô ly còn mới, chưa sử dụng', description:'Gồm 5 quyển vở mới, ưu tiên học sinh thực sự cần.', name:'Học sinh', className:'10A2', tradeType:'Cho tặng', category:'Vở', price:0, date:'09/08/2026 18:05', dateTs:1786273500000, hasImage:true, favoriteCount:14, ownerReputationScore:9.4, ownerReputationLabel:'Rất tốt', rankScore:90, aiScore:93, recommendationReason:'Cho tặng miễn phí và chủ bài có mức uy tín cao.' },
  { id:'UI-007', title:'Bút highlight 6 màu - đổi lấy giấy note', description:'Bút đã dùng ít, màu còn rõ, muốn đổi lấy giấy note.', name:'Học sinh', className:'10A1', tradeType:'Trao đổi', category:'Bút', price:0, date:'09/08/2026 16:40', dateTs:1786268400000, hasImage:false, favoriteCount:3, ownerReputationScore:5.9, ownerReputationLabel:'Khá', rankScore:66, aiScore:72, recommendationReason:'Bài trao đổi nhỏ, phù hợp nhóm đồ dùng học tập hằng ngày.' },
  { id:'UI-008', title:'Sách Ngữ văn 10 tập 1 và tập 2', description:'Hai cuốn còn đầy đủ, có ghi chú bằng bút chì ở vài trang.', name:'Học sinh', className:'11A1', tradeType:'Bán giá rẻ', category:'Sách giáo khoa', price:45000, date:'09/08/2026 14:15', dateTs:1786259700000, hasImage:true, favoriteCount:11, ownerReputationScore:7.4, ownerReputationLabel:'Tốt', rankScore:83, aiScore:88, recommendationReason:'Giá thấp và cùng nhóm sách giáo khoa được quan tâm.' },
  { id:'UI-009', title:'Cho mượn bảng tuần hoàn hóa học khổ A3', description:'Có thể mượn trong 2 tuần để ôn tập.', name:'Học sinh', className:'11A4', tradeType:'Cho mượn', category:'Dụng cụ học tập', price:0, date:'09/08/2026 10:30', dateTs:1786246200000, hasImage:true, favoriteCount:2, ownerReputationScore:6.2, ownerReputationLabel:'Tốt', rankScore:62, aiScore:69, recommendationReason:'Phù hợp nhu cầu học ngắn hạn và có ảnh minh họa.' },
  { id:'UI-010', title:'Sách bài tập Toán 12 còn khoảng 90% mới', description:'Không rách, chỉ ghi một số đáp án bằng bút chì.', name:'Học sinh', className:'12A5', tradeType:'Bán giá rẻ', category:'Sách tham khảo', price:55000, date:'08/08/2026 21:20', dateTs:1786198800000, hasImage:true, favoriteCount:10, ownerReputationScore:8.0, ownerReputationLabel:'Rất tốt', rankScore:85, aiScore:90, recommendationReason:'Bài có độ mới tốt và nhiều lượt lưu.' },
  { id:'UI-011', title:'Tặng hộp bút vải màu xanh còn dùng tốt', description:'Khóa kéo bình thường, đã vệ sinh sạch.', name:'Học sinh', className:'10A3', tradeType:'Cho tặng', category:'Dụng cụ học tập', price:0, date:'08/08/2026 17:45', dateTs:1786185900000, hasImage:true, favoriteCount:6, ownerReputationScore:7.1, ownerReputationLabel:'Tốt', rankScore:73, aiScore:78, recommendationReason:'Cho tặng miễn phí, tình trạng được mô tả rõ.' },
  { id:'UI-012', title:'Đổi sách Sinh học 11 lấy sách Tin học 11', description:'Sách Sinh học còn tốt, muốn trao đổi trực tiếp tại trường.', name:'Học sinh', className:'11A3', tradeType:'Trao đổi', category:'Sách', price:0, date:'08/08/2026 15:05', dateTs:1786176300000, hasImage:false, favoriteCount:4, ownerReputationScore:6.7, ownerReputationLabel:'Tốt', rankScore:69, aiScore:75, recommendationReason:'Đúng mô hình trao đổi tài nguyên học tập giữa học sinh.' },
  { id:'UI-013', title:'Bộ sách giáo khoa lớp 10 đã bọc bìa', description:'Đủ các môn chính, một số cuốn có ghi chú nhẹ.', name:'Học sinh', className:'11A2', tradeType:'Bán giá rẻ', category:'Sách giáo khoa', price:180000, date:'08/08/2026 12:30', dateTs:1786167000000, hasImage:true, favoriteCount:15, ownerReputationScore:8.9, ownerReputationLabel:'Rất tốt', rankScore:91, aiScore:92, recommendationReason:'Bộ sách đầy đủ, có ảnh và nhiều lượt lưu.' },
  { id:'UI-014', title:'Cho mượn máy tính Casio fx-580VN X trong 1 tháng', description:'Máy dùng tốt, cần hoàn trả đúng thời gian đã thống nhất.', name:'Học sinh', className:'12A2', tradeType:'Cho mượn', category:'Đồ điện tử nhỏ', price:0, date:'08/08/2026 10:05', dateTs:1786158300000, hasImage:true, favoriteCount:20, ownerReputationScore:9.3, ownerReputationLabel:'Rất tốt', rankScore:98, aiScore:97, recommendationReason:'Nhu cầu cao, chủ bài uy tín và nhiều lượt lưu.' },
  { id:'UI-015', title:'Tặng sách luyện đọc tiếng Anh trình độ cơ bản', description:'Sách có bài đọc và từ vựng, phù hợp tự học.', name:'Học sinh', className:'10A5', tradeType:'Cho tặng', category:'Sách tham khảo', price:0, date:'07/08/2026 19:50', dateTs:1786107000000, hasImage:false, favoriteCount:8, ownerReputationScore:7.7, ownerReputationLabel:'Tốt', rankScore:77, aiScore:82, recommendationReason:'Tài nguyên tự học miễn phí, phù hợp nhiều học sinh.' },
  { id:'UI-016', title:'Bán giá rẻ balo học sinh màu đen', description:'Balo còn chắc chắn, khóa kéo hoạt động bình thường.', name:'Học sinh', className:'12A4', tradeType:'Bán giá rẻ', category:'Khác', price:95000, date:'07/08/2026 17:10', dateTs:1786097400000, hasImage:true, favoriteCount:5, ownerReputationScore:5.6, ownerReputationLabel:'Khá', rankScore:64, aiScore:68, recommendationReason:'Có ảnh minh họa và mô tả tình trạng rõ.' },
  { id:'UI-017', title:'Đổi bộ bút chì kỹ thuật lấy thước vẽ', description:'Bút chì còn tốt, phù hợp vẽ kỹ thuật.', name:'Học sinh', className:'11A5', tradeType:'Trao đổi', category:'Bút', price:0, date:'07/08/2026 13:30', dateTs:1786084200000, hasImage:true, favoriteCount:3, ownerReputationScore:4.9, ownerReputationLabel:'Khá', rankScore:59, aiScore:65, recommendationReason:'Đúng nhóm dụng cụ vẽ và trao đổi ngang giá trị sử dụng.' },
  { id:'UI-018', title:'Cho mượn atlas Địa lí Việt Nam để ôn thi', description:'Atlas còn sạch, ưu tiên mượn tối đa 3 tuần.', name:'Học sinh', className:'12A1', tradeType:'Cho mượn', category:'Sách', price:0, date:'07/08/2026 09:40', dateTs:1786070400000, hasImage:false, favoriteCount:7, ownerReputationScore:8.4, ownerReputationLabel:'Rất tốt', rankScore:80, aiScore:85, recommendationReason:'Phù hợp học sinh lớp 12 và nhu cầu ôn tập ngắn hạn.' },
];
